# -*- coding: utf-8 -*-
"""sle_ml_master_pipeline.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LExw1MGqNyi9FCGGmc8RIc2vqypYljkj
"""

"""
=============================================================================
Master Machine Learning Pipeline for SLE Flare vs. Remission Classification
=============================================================================
Study: Integrative Plasma Proteomics and Myeloid-Interferon Profiling in SLE
Model: Random Forest Classifier
Features: 5-Marker Biosignature (COL18A1, HYOU1, IGHG4, FLNA, SH3BGRL3)
Validation: LOOCV, Repeated Stratified K-Fold, Permutation, Bootstrapping
Explainability: SHAP Values, PCA Decision Boundaries

Author: [Abhibroto Karmakar]
=============================================================================
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Scikit-learn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import LeaveOneOut, RepeatedStratifiedKFold, permutation_test_score
from sklearn.metrics import (accuracy_score, confusion_matrix, roc_curve, auc, cohen_kappa_score)
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# SHAP for Explainable AI
import shap

# --- GLOBAL SETTINGS ---
plt.rcParams['font.family'] = 'Arial'
sns.set_context("paper", font_scale=1.2)
np.random.seed(42)
PALETTE = {'Flare': '#FF3131', 'Remission': '#00BFFF'}

# ==========================================
# 1. DATA LOADER & PREPROCESSING
# ==========================================
def load_and_preprocess_data(filepath="SLE_16_ML.xlsx"):
    """
    Attempts to load the real dataset. If not found, generates a synthetic
    dataset mirroring the statistical properties of the 5-marker biosignature
    to ensure the code is fully reproducible by peer reviewers.
    """
    features = ['COL18A1', 'HYOU1', 'IGHG4', 'FLNA', 'SH3BGRL3']

    if os.path.exists(filepath):
        print(f"Loading actual data from {filepath}...")
        df = pd.read_excel(filepath)
        df['Label'] = df['BILAG Score'].apply(lambda x: 1 if x >= 10 else 0)
        df['Condition'] = df['Label'].map({1: 'Flare', 0: 'Remission'})
    else:
        print(f"File {filepath} not found. Generating reproducible synthetic cohort...")
        # Synthetic data generation for reviewers testing the code
        data = {
            'Condition': ['Flare']*8 + ['Remission']*8,
            'BILAG Score': [15, 14, 18, 12, 16, 13, 10, 15, 2, 4, 5, 4, 3, 5, 4, 2],
            'COL18A1': np.concatenate([np.random.normal(23, 1.5, 8), np.random.normal(19, 1.5, 8)]),
            'HYOU1': np.concatenate([np.random.normal(15, 1.5, 8), np.random.normal(11, 1.5, 8)]),
            'IGHG4': np.concatenate([np.random.normal(9, 1, 8), np.random.normal(14, 1, 8)]),
            'FLNA': np.concatenate([np.random.normal(8, 0.8, 8), np.random.normal(11, 0.8, 8)]),
            'SH3BGRL3': np.concatenate([np.random.normal(6, 1, 8), np.random.normal(9, 1, 8)])
        }
        df = pd.DataFrame(data)
        df['Label'] = df['Condition'].map({'Flare': 1, 'Remission': 0})

    X = df[features]
    y = df['Label']

    # Z-Score Normalization
    scaler = StandardScaler()
    X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=features)

    return df, X_scaled, y, features

# ==========================================
# 2. CORE ML: LOOCV & METRICS
# ==========================================
def run_loocv_evaluation(X_scaled, y):
    print("\n--- 1. Running Leave-One-Out Cross-Validation ---")
    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    loo = LeaveOneOut()

    y_true, y_pred, y_prob = [], [], []
    for train_idx, test_idx in loo.split(X_scaled):
        rf.fit(X_scaled.iloc[train_idx], y.iloc[train_idx])
        y_pred.append(rf.predict(X_scaled.iloc[test_idx])[0])
        y_prob.append(rf.predict_proba(X_scaled.iloc[test_idx])[0][1])
        y_true.append(y.iloc[test_idx].values[0])

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    acc = accuracy_score(y_true, y_pred)
    kappa = cohen_kappa_score(y_true, y_pred)
    roc_auc = auc(*roc_curve(y_true, y_prob)[:2])

    print(f"Accuracy:    {acc*100:.2f}%")
    print(f"Sensitivity: {(tp/(tp+fn))*100:.2f}%")
    print(f"Specificity: {(tn/(tn+fp))*100:.2f}%")
    print(f"Cohen Kappa: {kappa:.3f}")
    print(f"Mean AUROC:  {roc_auc:.3f}")

    # Fig ML_5d: Confusion Matrix
    plt.figure(figsize=(5, 4))
    sns.heatmap([[tn, fp], [fn, tp]], annot=True, fmt='d', cmap='Blues',
                xticklabels=['Remission', 'Flare'], yticklabels=['Remission', 'Flare'])
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.title('Fig ML_5d: LOOCV Confusion Matrix', fontweight='bold')
    plt.tight_layout()
    plt.savefig('Fig_ML_5d_Confusion_Matrix.png', dpi=300)
    plt.close()

    return y_true, y_prob

# ==========================================
# 3. ROBUSTNESS: PERMUTATION & SENSITIVITY
# ==========================================
def run_robustness_checks(X_scaled, y):
    print("\n--- 2. Running Robustness & Stress Tests ---")
    rf = RandomForestClassifier(n_estimators=100, random_state=42)

    # Repeated K-Fold Sensitivity
    rskf = RepeatedStratifiedKFold(n_splits=4, n_repeats=50, random_state=42)
    acc_scores = [accuracy_score(y.iloc[test], rf.fit(X_scaled.iloc[train], y.iloc[train]).predict(X_scaled.iloc[test]))
                  for train, test in rskf.split(X_scaled, y)]
    print(f"Stress Test (4-Fold x 50) Mean Accuracy: {np.mean(acc_scores)*100:.2f}%")

    # Permutation Test
    score, perm_scores, pval = permutation_test_score(
        rf, X_scaled, y, scoring="accuracy", cv=LeaveOneOut(), n_permutations=1000, random_state=42)
    print(f"Permutation p-value: {pval:.4f}")

    plt.figure(figsize=(6, 4))
    plt.hist(perm_scores, bins=20, color='gray', edgecolor='black', alpha=0.7)
    plt.axvline(score, color='red', linestyle='--', lw=2, label=f'True Acc ({score:.2f})')
    plt.title('Fig ML_5c: Permutation Test (n=1000)', fontweight='bold')
    plt.legend()
    plt.tight_layout()
    plt.savefig('Fig_ML_5c_Permutation.png', dpi=300)
    plt.close()

# ==========================================
# 4. VISUALIZATIONS (Violins, PCA, SHAP, ROC)
# ==========================================
def generate_visualizations(df, X_scaled, y, features, y_true, y_prob):
    print("\n--- 3. Generating ML Visualizations ---")

    # 1. Fig ML_1c: Violin Plots
    fig, axes = plt.subplots(1, 5, figsize=(15, 4))
    for i, feat in enumerate(features):
        sns.violinplot(x='Condition', y=feat, data=df, ax=axes[i], palette=PALETTE, inner="points")
        axes[i].set_title(feat, fontweight='bold')
        axes[i].set_xlabel('')
        if i > 0: axes[i].set_ylabel('')
    plt.suptitle('Fig ML_1c: Biomarker Distribution', fontweight='bold', y=1.05)
    sns.despine()
    plt.tight_layout()
    plt.savefig('Fig_ML_1c_Violins.png', dpi=300)
    plt.close()

    # 2. Fig 7b: COL18A1 Diagnostic Cut-off
    fpr, tpr, thresholds = roc_curve(df['Label'], df['COL18A1'])
    opt_thresh = thresholds[np.argmax(tpr - fpr)]
    plt.figure(figsize=(5, 5))
    sns.boxplot(x='Condition', y='COL18A1', data=df, palette=PALETTE)
    plt.axhline(opt_thresh, color='red', linestyle='--', label=f'Cut-off > {opt_thresh:.2f}')
    plt.title('Fig 7b: Diagnostic Cut-off (COL18A1)', fontweight='bold')
    plt.legend()
    plt.tight_layout()
    plt.savefig('Fig_7b_COL18A1_Cutoff.png', dpi=300)
    plt.close()
    print(f"Optimal Cut-off for COL18A1: > {opt_thresh:.2f}")

    # 3. Fig ML_4a: PCA Decision Boundary
    pca = PCA(n_components=2)
    X_pca = pca.fit_transform(X_scaled)
    clf = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_pca, y)

    xx, yy = np.meshgrid(np.arange(X_pca[:,0].min()-1, X_pca[:,0].max()+1, 0.05),
                         np.arange(X_pca[:,1].min()-1, X_pca[:,1].max()+1, 0.05))
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

    plt.figure(figsize=(6, 5))
    plt.contourf(xx, yy, Z, alpha=0.2, cmap='coolwarm')
    scatter = plt.scatter(X_pca[:,0], X_pca[:,1], c=y, cmap='coolwarm', edgecolor='k', s=80)
    plt.xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)')
    plt.ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)')
    plt.title('Fig ML_4a: AI Decision Boundary', fontweight='bold')
    plt.legend(handles=scatter.legend_elements()[0], labels=['Remission', 'Flare'])
    plt.tight_layout()
    plt.savefig('Fig_ML_4a_PCA_Boundary.png', dpi=300)
    plt.close()

    # 4. Fig ML_4b: SHAP Values
    rf_full = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_scaled, y)
    explainer = shap.TreeExplainer(rf_full)
    shap_vals = explainer.shap_values(X_scaled)[1] # Get class 1 (Flare) values

    plt.figure(figsize=(8, 5))
    shap.summary_plot(shap_vals, X_scaled, show=False)
    plt.title('Fig ML_4b: SHAP Feature Importance', fontweight='bold')
    plt.tight_layout()
    plt.savefig('Fig_ML_4b_SHAP.png', dpi=300)
    plt.close()

    # 5. Fig ML_5b: Bootstrapped ROC
    n_bootstraps = 1000
    base_fpr = np.linspace(0, 1, 101)
    tprs = []

    # Calculate LOOCV probabilities for bootstrapping
    y_prob_cv = np.zeros(len(y))
    loo = LeaveOneOut()
    for train, test in loo.split(X_scaled):
        rf_full.fit(X_scaled.iloc[train], y.iloc[train])
        y_prob_cv[test] = rf_full.predict_proba(X_scaled.iloc[test])[0, 1]

    y_true_arr = np.array(y)
    for _ in range(n_bootstraps):
        idx = np.random.randint(0, len(y_prob_cv), len(y_prob_cv))
        if len(np.unique(y_true_arr[idx])) < 2: continue
        fpr_b, tpr_b, _ = roc_curve(y_true_arr[idx], y_prob_cv[idx])
        tpr_interp = np.interp(base_fpr, fpr_b, tpr_b)
        tpr_interp[0] = 0.0
        tprs.append(tpr_interp)

    tprs = np.array(tprs)
    mean_tprs = tprs.mean(axis=0)
    mean_tprs[-1] = 1.0
    std_tprs = tprs.std(axis=0)
    tprs_upper = np.minimum(mean_tprs + 1.96 * std_tprs, 1)
    tprs_lower = np.maximum(mean_tprs - 1.96 * std_tprs, 0)

    plt.figure(figsize=(6, 5))
    plt.plot(base_fpr, mean_tprs, 'b', lw=2, label=f'Mean ROC (AUC={auc(base_fpr, mean_tprs):.2f})')
    plt.fill_between(base_fpr, tprs_lower, tprs_upper, color='blue', alpha=0.2, label='95% CI')
    plt.plot([0,1], [0,1], 'r--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Fig ML_5b: Bootstrapped ROC Curve', fontweight='bold')
    plt.legend(loc='lower right')
    plt.tight_layout()
    plt.savefig('Fig_ML_5b_Bootstrapped_ROC.png', dpi=300)
    plt.close()

# ==========================================
# 5. CLINICAL CORRELATION
# ==========================================
def plot_clinical_correlation(df, features):
    print("\n--- 4. Generating Clinical Correlation Heatmap ---")
    corr_df = df[features + ['BILAG Score']]
    correlations = corr_df.corr(method='pearson')[['BILAG Score']].drop('BILAG Score')
    correlations = correlations.sort_values(by='BILAG Score', ascending=False)

    plt.figure(figsize=(4, 5))
    sns.heatmap(correlations, annot=True, cmap='vlag', center=0, fmt='.2f', cbar_kws={'label': 'Pearson r'})
    plt.title('Fig ML_2: Correlation with\nEasy-BILAG Score', fontweight='bold')
    plt.tight_layout()
    plt.savefig('Fig_ML_2_Correlation.png', dpi=300)
    plt.close()

# ==========================================
# MAIN EXECUTION SCRIPT
# ==========================================
if __name__ == "__main__":
    print("Starting SLE Machine Learning Pipeline...")

    # 1. Load Data
    df, X_scaled, y, features = load_and_preprocess_data()

    # 2. Train & Evaluate
    y_true, y_prob = run_loocv_evaluation(X_scaled, y)

    # 3. Robustness Tests
    run_robustness_checks(X_scaled, y)

    # 4. Generate All ML Visualizations
    generate_visualizations(df, X_scaled, y, features, y_true, y_prob)

    # 5. Generate Clinical Correlations
    plot_clinical_correlation(df, features)

    print("\n✅ Pipeline successfully completed! All figures saved as PNG files in the current directory.")